### PR TITLE
Add timestamp() expression support

### PR DESCRIPTION
**Pull request by RoeyMaor**
**Release note**:
```
Add timestamp() expression support.
```

---
This change is [Reviewable](https://reviewable.io/reviews/istio/mixer/1383)

### CODE REVIEW

**Comment by douglas-reid** [comment]
@RoeyMaor would you mind updating the PR description to have the release note be a single liner. I'm thinking the easiest thing to do would be to move the current release note to the description and replace it with a single "Add timestamp() expression support" (or similar).

**Comment by douglas-reid** [comment]
All: conceptually, do we expect that operators will want to have a static fallback time, or would something like `now()` be more appropriate?  I don't see any reason not to support both, mostly just curious.

**Comment by mandarjog** [comment]
I think most use cases call for `request.now` or similar.
However having a way to create literals for value types is useful.

**Comment by RoeyMaor** [comment]
waiting for https://github.com/istio/mixer/pull/1429 to be merged

**Comment by RoeyMaor** [comment]
@mandarjog

**Pull request merged**
