### PR TITLE
A bit of refactoring/cleanup.

### PR DESCRIPTION
**Pull request by geeknoid**
This makes the code for the mixc and mixs commands consistent in
style and form.

No functional changes.

---
This change is [Reviewable](https://reviewable.io/reviews/istio/mixer/93)

### CODE REVIEW

**Comment by douglas-reid** [comment]
:lgtm:

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[cmd/client/check.go, line 26 at r1](https://reviewable.io:443/reviews/istio/mixer/93#-KZXmoFl1G3pz7lofDVc:-KZXmoFl1G3pz7lofDVd:bpvjang) ([raw file](https://github.com/istio/mixer/blob/8b3cb7da8c93ff7efc96ac0e8c73bc55b4b837c1/cmd/client/check.go#L26)):*
> ```Go
> )
> 
> func checkCmd(rootArgs *rootArgs, errorf func(format string, a ...interface{})) *cobra.Command {
> ```

i wonder if it is worth defining something like: `type errorFn func(format string, args ...interface{})` to reduce the amount of repetition. That might make this `func checkCmd(rootArgs *rootArgs, errorf errorFn)) *cobra.Command {.

---

*[cmd/client/main.go, line 69 at r1](https://reviewable.io:443/reviews/istio/mixer/93#-KZXnlZt7f-9QYr4-BDx:-KZXnlZt7f-9QYr4-BDy:bxmi0pl) ([raw file](https://github.com/istio/mixer/blob/8b3cb7da8c93ff7efc96ac0e8c73bc55b4b837c1/cmd/client/main.go#L69)):*
> ```Go
> 	rootCmd.PersistentFlags().StringVarP(&rootArgs.boolAttributes, "bool_attributes", "b", "", "List of name/value bool attributes specified as name1=value1,name2=value2,...")
> 	rootCmd.PersistentFlags().StringVarP(&rootArgs.timestampAttributes, "timestamp_attributes", "t", "", "List of name/value timestamp attributes specified as name1=value1,name2=value2,...")
> 	rootCmd.PersistentFlags().StringVarP(&rootArgs.bytesAttributes, "bytes_attributes", "", "", "List of name/value bytes attributes specified as name1=b0:b1:b3,name2=b4:b5:b6,...")
> ```

BTW: it'd be really cool if there was only `--attributes` and we could auto-detect type.

---

*[cmd/client/main.go, line 84 at r1](https://reviewable.io:443/reviews/istio/mixer/93#-KZXo5BfsWHyil957VDx:-KZXo5BfsWHyil957VDy:b-xuo6vr) ([raw file](https://github.com/istio/mixer/blob/8b3cb7da8c93ff7efc96ac0e8c73bc55b4b837c1/cmd/client/main.go#L84)):*
> ```Go
> 	withArgs(os.Args[1:],
> 		func(format string, a ...interface{}) {
> 			glog.Errorf(format+"\n", a...)
> ```

fwiw, i think glog auto-adds the "\n" if it detects the last byte is not "\n".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/istio/mixer/93#-:-KZXpNl6Z-LneFTE5Yzr:bnfp4nl)*

**Comment by geeknoid** [comment]
*[cmd/client/main.go, line 69 at r1](https://reviewable.io:443/reviews/istio/mixer/93#-KZXnlZt7f-9QYr4-BDx:-KZXt7ZnyBU1Am9Gt6_l:b-523dg9) ([raw file](https://github.com/istio/mixer/blob/8b3cb7da8c93ff7efc96ac0e8c73bc55b4b837c1/cmd/client/main.go#L69)):*
<details><summary><i>Previously, douglas-reid (Douglas Reid) wrote…</i></summary><blockquote>

BTW: it'd be really cool if there was only `--attributes` and we could auto-detect type.
</blockquote></details>

I'll look into it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/istio/mixer/93)*

**Comment by geeknoid** [comment]
Review status: 2 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[cmd/client/check.go, line 26 at r1](https://reviewable.io:443/reviews/istio/mixer/93#-KZXmoFl1G3pz7lofDVc:-KZXt3rSVKdYfjWfWtIj:b-896fix) ([raw file](https://github.com/istio/mixer/blob/8b3cb7da8c93ff7efc96ac0e8c73bc55b4b837c1/cmd/client/check.go#L26)):*
<details><summary><i>Previously, douglas-reid (Douglas Reid) wrote…</i></summary><blockquote>

i wonder if it is worth defining something like: `type errorFn func(format string, args ...interface{})` to reduce the amount of repetition. That might make this `func checkCmd(rootArgs *rootArgs, errorf errorFn)) *cobra.Command {.
</blockquote></details>

Done.

---

*[cmd/client/main.go, line 84 at r1](https://reviewable.io:443/reviews/istio/mixer/93#-KZXo5BfsWHyil957VDx:-KZXtCgqhoPe6gwSakFZ:b-896fix) ([raw file](https://github.com/istio/mixer/blob/8b3cb7da8c93ff7efc96ac0e8c73bc55b4b837c1/cmd/client/main.go#L84)):*
<details><summary><i>Previously, douglas-reid (Douglas Reid) wrote…</i></summary><blockquote>

fwiw, i think glog auto-adds the "\n" if it detects the last byte is not "\n".
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/istio/mixer/93)*

**Comment by douglas-reid** [comment]
LGTM

**Comment by douglas-reid** [comment]
OK

---

Review status: 2 of 9 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/istio/mixer/93#-:-KZXybT3PoUrBNHY5aK-:b32w0x)*

**Comment by douglas-reid** [comment]
Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/istio/mixer/93)*

**Pull request merged**
