### PR TITLE
Remove the golang genproto dependency from WORKSPACE.

### PR DESCRIPTION
**Pull request by douglas-reid**
This CL transitions to using gogoslick for the google/rpc/code.proto
messages. In doing so, it also removes the remaining uses of the
standard golang generated code for protos from the codebase.

Tested with:

```shell
$ bazel clean
$ bazel test ...
```

---
This change is [Reviewable](https://reviewable.io/reviews/istio/mixer/295)

### CODE REVIEW

**Comment by ZackButcher** [comment]
I'm not sure I love collapsing the codes into the rpc namespace along with this. Some of the `code`s read better (e.g. `rpc.FAILED_PRECONDITION`) but others not so much (e.g. `rpc.INTERNAL`; IMO `code.INTERNAL` is more clear). It also makes it less obvious we're working with the canonical error codes. Maybe it's just because I'm used to working `code`.

**Comment by douglas-reid** [comment]
it looks like the `option go` parts of the proto files are ignored by the current protoc setup. Not entirely sure why. I can dig further.

FWIW, `code.proto` declares its package as `google.rpc`. The collapsing then happens, in part, from the gogoslick options.

**Comment by ZackButcher** [comment]
I don't think it's worth blocking this PR over `code` vs `rpc`.

**Comment by douglas-reid** [comment]
OK. Then I'll submit now and maybe next week during a down moment will play with separating.

**Pull request merged**
