### PR TITLE
New adapter & better adapter tests.

### PR DESCRIPTION
**Pull request by geeknoid**
- Added the genericListChecker adapter which works based on a
list specified in config

- Made the adapter unit tests work against builders instead of
the adapters directly, which increases unit test coverage

- Add common builder invariant test

- Fixed various dependency issues in the Makefile

---
This change is [Reviewable](https://reviewable.io/reviews/istio/mixer/24)

### CODE REVIEW

**Comment by douglas-reid** [comment]
Review status: 0 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[adapters/builder_test.go, line 1 at r1](https://reviewable.io:443/reviews/istio/mixer/24#-KY-qhVuwugYx1D9JB01:-KY-qhVvTivE5ji_L8B5:b-6gvfep) ([raw file](https://github.com/istio/mixer/blob/843f2c27566b6f5d6d0ccb3b064abe7430ccfa66/adapters/builder_test.go#L1)):*
> ```Go
> // Copyright 2016 Google Inc.
> ```

Is this file needed? It seems to duplicate adapters/testutils/builder.go.

---

*[adapters/factMapper/builder_test.go, line 29 at r1](https://reviewable.io:443/reviews/istio/mixer/24#-KY-rdqEQ0eDHl2skDF4:-KY-rdqEQ0eDHl2skDF5:bcnd9dh) ([raw file](https://github.com/istio/mixer/blob/843f2c27566b6f5d6d0ccb3b064abe7430ccfa66/adapters/factMapper/builder_test.go#L29)):*
> ```Go
> }
> 
> func TestNoRules(t *testing.T) {
> ```

Per our own guidelines:

"Table-driven tests are preferred for testing multiple scenarios/inputs."

Should these tests be refactored to have a single struct for test setup?

---

*[adapters/genericListChecker/builder_test.go, line 29 at r1](https://reviewable.io:443/reviews/istio/mixer/24#-KY-s5HoPa0o4UAupMzI:-KY-s5HoPa0o4UAupMzJ:b703b89) ([raw file](https://github.com/istio/mixer/blob/843f2c27566b6f5d6d0ccb3b064abe7430ccfa66/adapters/genericListChecker/builder_test.go#L29)):*
> ```Go
> }
> 
> func TestWhitelistWithOverrides(t *testing.T) {
> ```

See previous comment re: table-driven tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/istio/mixer/24)*

**Comment by geeknoid** [comment]
I deleted the extraneous file, it was a turd. I opened issue #25 to track using a table-driven approach to my tests. I'll clean those up this weekend.

Thanks.

**Comment by douglas-reid** [comment]
Review status: 0 of 12 files reviewed at latest revision, 3 unresolved discussions.

---

*[adapters/factMapper/builder_test.go, line 29 at r1](https://reviewable.io:443/reviews/istio/mixer/24#-KY-rdqEQ0eDHl2skDF4:-KY00ZOqSRcm8dfzCG9i:b2a4evf) ([raw file](https://github.com/istio/mixer/blob/843f2c27566b6f5d6d0ccb3b064abe7430ccfa66/adapters/factMapper/builder_test.go#L29)):*
<details><summary><i>Previously, douglas-reid (Douglas Reid) wrote…</i></summary><blockquote>

Per our own guidelines:

"Table-driven tests are preferred for testing multiple scenarios/inputs."

Should these tests be refactored to have a single struct for test setup?
</blockquote></details>

Issue #25 filed for this. Resolving for now.

---

*[adapters/genericListChecker/adapter.go, line 1 at r2](https://reviewable.io:443/reviews/istio/mixer/24#-KY00oUNW07N-DwsC_Hj:-KY00oUNW07N-DwsC_Hk:b-hzgeif) ([raw file](https://github.com/istio/mixer/blob/d20507c1aeee2827536187f5204d6e8fba46f615/adapters/genericListChecker/adapter.go#L1)):*
> ```Go
> // Copyright 2016 Google Ina.
> ```

s/Ina/Inc ?

---

*[adapters/genericListChecker/builder.go, line 31 at r2](https://reviewable.io:443/reviews/istio/mixer/24#-KY04546AwIMYnRJH6mU:-KY04546AwIMYnRJH6mV:b4sf1hw) ([raw file](https://github.com/istio/mixer/blob/d20507c1aeee2827536187f5204d6e8fba46f615/adapters/genericListChecker/builder.go#L31)):*
> ```Go
> 	// Otherwise, when WhitelistMode is false, an item succeeds a
> 	// check call if it is not in the list.
> 	WhitelistMode bool
> ```

given that the default value of bool is 'false', should we change this behavior?  should Lists default to whitelist behavior?

---

*[adapters/genericListChecker/builder_test.go, line 29 at r1](https://reviewable.io:443/reviews/istio/mixer/24#-KY-s5HoPa0o4UAupMzI:-KY04nXUMpLXkjzHunkv:boguiyz) ([raw file](https://github.com/istio/mixer/blob/843f2c27566b6f5d6d0ccb3b064abe7430ccfa66/adapters/genericListChecker/builder_test.go#L29)):*
<details><summary><i>Previously, douglas-reid (Douglas Reid) wrote…</i></summary><blockquote>

See previous comment re: table-driven tests.
</blockquote></details>

marking as resolved based on issue #25 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/istio/mixer/24)*

**Comment by geeknoid** [comment]
Review status: 0 of 12 files reviewed at latest revision, 3 unresolved discussions.

---

*[adapters/genericListChecker/adapter.go, line 1 at r2](https://reviewable.io:443/reviews/istio/mixer/24#-KY00oUNW07N-DwsC_Hj:-KY080xv9ymJ68OjTUlZ:b-896fix) ([raw file](https://github.com/istio/mixer/blob/d20507c1aeee2827536187f5204d6e8fba46f615/adapters/genericListChecker/adapter.go#L1)):*
<details><summary><i>Previously, douglas-reid (Douglas Reid) wrote…</i></summary><blockquote>

s/Ina/Inc ?
</blockquote></details>

Done.

---

*[adapters/genericListChecker/builder.go, line 31 at r2](https://reviewable.io:443/reviews/istio/mixer/24#-KY04546AwIMYnRJH6mU:-KY07T1-rhV7maIAfnMk:b-unnab) ([raw file](https://github.com/istio/mixer/blob/d20507c1aeee2827536187f5204d6e8fba46f615/adapters/genericListChecker/builder.go#L31)):*
<details><summary><i>Previously, douglas-reid (Douglas Reid) wrote…</i></summary><blockquote>

given that the default value of bool is 'false', should we change this behavior?  should Lists default to whitelist behavior?
</blockquote></details>

Do you see an advantage in defaulting one way or another? I could change this field to call it BlacklistMode instead. Or maybe, we should use a more descriptive term such as "CheckForAbsence"?

---

*[adapters/builder_test.go, line 1 at r1](https://reviewable.io:443/reviews/istio/mixer/24#-KY-qhVuwugYx1D9JB01:-KY07wVbMTk0mCBmDhDn:b-896fix) ([raw file](https://github.com/istio/mixer/blob/843f2c27566b6f5d6d0ccb3b064abe7430ccfa66/adapters/builder_test.go#L1)):*
<details><summary><i>Previously, douglas-reid (Douglas Reid) wrote…</i></summary><blockquote>

Is this file needed? It seems to duplicate adapters/testutils/builder.go.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/istio/mixer/24)*

**Comment by douglas-reid** [comment]
Review status: 0 of 12 files reviewed at latest revision, 3 unresolved discussions.

---

*[adapters/genericListChecker/builder.go, line 31 at r2](https://reviewable.io:443/reviews/istio/mixer/24#-KY04546AwIMYnRJH6mU:-KY0E4LeIqB45jL8mnjr:bumosvu) ([raw file](https://github.com/istio/mixer/blob/d20507c1aeee2827536187f5204d6e8fba46f615/adapters/genericListChecker/builder.go#L31)):*
<details><summary><i>Previously, geeknoid (Martin Taillefer) wrote…</i></summary><blockquote>

Do you see an advantage in defaulting one way or another? I could change this field to call it BlacklistMode instead. Or maybe, we should use a more descriptive term such as "CheckForAbsence"?
</blockquote></details>

Probably need more input. My initial gut reaction was that lists would be used for whitelist purposes more than blacklist purposes and so we would want whitelisting to be the default, but I don't know that that reaction is correct.

I think Blacklist is well-enough understood.

@mandarjog what do you think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/istio/mixer/24)*

**Comment by geeknoid** [comment]
Can I go ahead with this PR?

**Comment by douglas-reid** [comment]
Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[adapters/genericListChecker/builder.go, line 31 at r2](https://reviewable.io:443/reviews/istio/mixer/24#-KY04546AwIMYnRJH6mU:-KYFqecZmhqsOALbl2zj:buw39w8) ([raw file](https://github.com/istio/mixer/blob/d20507c1aeee2827536187f5204d6e8fba46f615/adapters/genericListChecker/builder.go#L31)):*
<details><summary><i>Previously, douglas-reid (Douglas Reid) wrote…</i></summary><blockquote>

Probably need more input. My initial gut reaction was that lists would be used for whitelist purposes more than blacklist purposes and so we would want whitelisting to be the default, but I don't know that that reaction is correct.

I think Blacklist is well-enough understood.

@mandarjog what do you think?
</blockquote></details>

Postponing this issue for now. @mandarjog will address in a future PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/istio/mixer/24)*

**Comment by douglas-reid** [comment]
:lgtm:

---

Review status: 0 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/istio/mixer/24#-:-KYFqxQ6zM-htXMUfk2U:bnfp4nl)*

**Comment by douglas-reid** [comment]
Reviewed 14 of 16 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/istio/mixer/24)*

**Comment by douglas-reid** [comment]
LGTM

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/istio/mixer/24#-:-KYFrhQ_5UzlQ3jLwwBl:bb6ywmx)*

**Pull request merged**
