### PR TITLE
Update the attribute protocol around stringmaps to enable delta stringmaps

### PR DESCRIPTION
**Pull request by geeknoid**
This change is [Reviewable](https://reviewable.io/reviews/istio/mixer/311)

### CODE REVIEW

**Comment by geeknoid** [comment]
This can be achieved with the delete feature.

In a single request, you specify you'd like to delete attribute FOO, and
then supply a string map attribute FOO which holds the new value you want.

Supporting these semantics is why I moved the block of delete functionality
up in the rootBag.update method.

Makes sense?

**Comment by qiwzhang** [comment]
Does this feature subject to this "attribute_context" field:

https://github.com/istio/api/blob/master/mixer/v1/attributes.proto#L84

If it is 0,  is it always "replacement"?

If so, if is fine for me.  The issue is: client is NOT ready for delta update yet.

BTW, we may need deleted_keys for string_map. Otherwise, if a key is removed, we have to do whole map replacement.

**Comment by geeknoid** [comment]
I'm not sure what you're asking about regarding attribute_context. An
attribute_context of 0 currently has no special semantics. Each individual
stream can have N parallel attribute contexts and operate on them
independently. There is currently no way to delete attribute contexts.

Yes, if we find that we need to often delete keys from a string map, we'll
need to figure out how to encode that. For the moment, I think we can live
without that feature.

Once I check in this change, you will need to add a delete_attribute item
for each string map you send in order to maintain replacement semantics.
Once the client knows how to do string map deltas, then you can remove the
delete_attribute items.

**Comment by qiwzhang** [comment]
client code is not doing "delta_update" yet.  I through 0 attribute_context means 0 context, all attributes are in the request body.  If mixer is not doing that, we may have to support it.

**Comment by qiwzhang** [comment]
I created issue https://github.com/istio/mixer/issues/313 to request such support.  The current communication between proxy and mixer is broken, unless proxy can quickly implement delta update.

**Comment by geeknoid** [comment]
The client code can just set reset_context to true in every request it
sends. This has the effect of treating the whole request as a replacement
rather than a delta.

**Pull request merged**
