### PR TITLE
typo

### PR DESCRIPTION
**Pull request by ryancox**
This change is [Reviewable](https://reviewable.io/reviews/istio/mixer/659)

### CODE REVIEW

**Comment by douglas-reid** [comment]
@ryancox would you mind updating this PR (should just be a button to click)? I think I can merge it after you do that, but at the moment, I have no way to help move this along.

**Comment by douglas-reid** [comment]
@ryancox would you mind merging again? i apparently missed the window from your update to before someone else merged. sorry about that.

**Comment by geeknoid** [comment]
Could you update your PR?

GitHub is telling me your branch is out of date and tells me to merge the latest changes into the branch, but it's not showing me the normal button to let me update the branch, so I can't do it...

**Comment by douglas-reid** [comment]
jenkins build mixer/e2e-smoketest

**Pull request merged**
