### PR TITLE
Make StringTable size expandable.

### PR DESCRIPTION
**Pull request by ozevren**
**Release note**:

```release-note
NONE
```

---
This change is [Reviewable](https://reviewable.io/reviews/istio/mixer/1338)

### CODE REVIEW

**Comment by ozevren** [comment]
Noticed this issue after looking at the code again. This change makes the StringTable size expandable.

**Comment by guptasu** [comment]
@ozevren if this needs to go in for 0.2, please ping on the Mixer slack asking the oncall to take a look and get this in.

**Comment by ozevren** [comment]
fixes #1355

**Comment by linsun** [comment]
what is the user impact of this for 0.2?  if not critical, i'd prefer to defer to 0.3.

**Comment by ozevren** [comment]
The user impact is big. The string table interns strings that are coming in
runtime. A fixed size means, over time the table will be full.

**Comment by geeknoid** [comment]
Yes, looks fine to me.

**Comment by mandarjog** [comment]
@ozevren successive failures, this needs to be investigated.

**Comment by kyessenov** [comment]
please investigate
/do-not-merge

**Comment by ozevren** [comment]
Retesting again.

**Comment by ozevren** [comment]
It looks like the previous failures were due to an issue that was fixed (fix: https://github.com/istio/mixer/commit/c99106271a77d89fa082fb58fa3a4be8a2de3d3f).

rebased on the latest commit, reran all the tests twice, and both passed. Planning to commit soon.

**Comment by ozevren** [comment]
Kuat, Lin, could one of you remove the do-not-merge label?

**Comment by mandarjog** [comment]
@kyessenov @linsun all tests pass. Previously it was failing on the duplicate config error, which has been fixed in another PR.

/lgtm

**Comment by kyessenov** [comment]
prow rebases before running tests. was the fixed not merged prior to running the tests?

**Comment by linsun** [comment]
I don't think i have permission to remove that label.

**Comment by ldemailly** [comment]
@ozevren can you what exactly ends up in idToString  - specifically are there strings in there that come from the request. for instance for an http incoming request, can any of:
- uri path
- header names
- header values
or any other unbound data come into those ?

**Comment by ozevren** [comment]
Yes. idToString currently captures strings that it ends up using in
evaluation of expressions. (It can be header names and or valeus)

**Comment by ldemailly** [comment]
so the whole attribute bag and each key and value in string maps end up in there whether used or not, are you sure ?

if so can we file a followup issue to cleanup as this will be ever growing memory / should show up as a memory leak ?

**Comment by ozevren** [comment]
No, not all of it. Only the ones used when evaluation a particular expression that is needed to resolve the request.

I've filed an issue and also have a potential short-term fix. 
https://github.com/istio/mixer/issues/1369
https://github.com/istio/mixer/pull/1370

**Pull request merged**
