### PR TITLE
Add cc_proto_library for api proto.

### PR DESCRIPTION
**Pull request by qiwzhang**
This change is [Reviewable](https://reviewable.io/reviews/istio/mixer/73)

### CODE REVIEW

**Comment by qiwzhang** [comment]
With this change, in my local, I can build

bazel build //api/v1:cc_proto

but I could not build

bazel build //api/v1:all

....
external/com_github_google_protobuf/src: warning: directory does not exist.
google/protobuf/any.proto: File not found.
google/rpc/status.proto: Import "google/protobuf/any.proto" was not found or had errors.
google/rpc/status.proto:89:12: "google.protobuf.Any" is not defined.
api/v1/check.proto: Import "google/rpc/status.proto" was not found or had errors.
api/v1/check.proto:37:3: "google.rpc.Status" is not defined.

**Comment by douglas-reid** [comment]
This PR, to me, is evidence that we should move the API surface out of the mixer repo into a separate repo.  It adds a ton of scaffolding to support c++, of which there is no code within the repo itself.

**Comment by douglas-reid** [comment]
@qiwzhang this appears to be because we now have multiple bits in the build pulling in the protobuf library in different ways.  I'll keep digging to find a workaround.

**Comment by douglas-reid** [comment]
Please take a look at #75. This should add the functionality needed.

**Pull request closed without merging**
