### PR TITLE
pull istio/istio from release-0.2 for e2e

### PR DESCRIPTION
**Pull request by yutongz**
**Release note**:

```release-note
none
```

release branch should be verified by e2e tests also from the corresponding release branch.

---
This change is [Reviewable](https://reviewable.io/reviews/istio/mixer/1449)

### CODE REVIEW

**Comment by mandarjog** [comment]
@yutongz does this mean we are no longer testing against `master` ?

**Comment by yutongz** [comment]
@mandarjog PRs to master are tested again master, release branches will be tested again release branches.

**Pull request merged**
