### PR TITLE
Add apicheck template

### PR DESCRIPTION
**Pull request by manlinl**
**Release note**:

```release-note
```

---
This change is [Reviewable](https://reviewable.io/reviews/istio/mixer/1410)

### CODE REVIEW

**Comment by manlinl** [comment]
The template is open. New fields for other form of auth attribute can be added as well. Are you suggesting something as generic as  'map<string, ValueType> dimensions' ? I had that idea but @geeknoid prefers something explicit.

**Comment by geeknoid** [comment]
You have to think of this as an object-oriented design pattern. Is there a way you can design the arguments for a check call to be generic such that completely different adapter implementations can be used?

In this case, perhaps all it means is that api_key should in fact be "credential" or something. And maybe api_operation just becomes "operation" so it's not directly associated with the API management thing.

**Comment by manlinl** [comment]
Template is in review, for now, close this PR.

**Pull request closed without merging**
