### PR TITLE
Fix linter issues

### PR DESCRIPTION
**Pull request by douglas-reid**
```
I0804 03:11:09.980] Running linters
I0804 03:11:10.031] Running linters on all files.
I0804 03:15:34.042] pkg/adapterManager/manager.go:332:2:warning: ineffectual assignment to requestBag (ineffassign)
I0804 03:16:02.804] tools/codegen/tools/codegen/pkg/modelgen/model.go:129:12:warning: should use strconv.Itoa instead of strconv.FormatInt (S1015) (gosimple)
E0804 03:17:03.063] Build failed
```

These are blocking transition to Prow.

---
This change is [Reviewable](https://reviewable.io/reviews/istio/mixer/1012)

### CODE REVIEW

**Comment by sebastienvas** [comment]
Thanks for doing this. I guess I could have done that. I just was not sure why the nil statement was there to begin with.

**Comment by douglas-reid** [comment]
@sebastienvas the signature of that method changed recently. `requestBag` was a pointer. Now, it is not.

**Comment by sebastienvas** [comment]
I guess recreating the cluster did not help.

**Comment by douglas-reid** [comment]
build mixer/e2e-smoketest

**Pull request merged**
