### PR TITLE
Add repositories.bzl to remove boilerplate in BUILD files

### LINKED ISSUE #99: Fix boilerplate goo in BUILD files for local istio_api usage

### PR DESCRIPTION
**Pull request by lizan**
Closes #99

---
This change is [Reviewable](https://reviewable.io/reviews/istio/mixer/101)

### CODE REVIEW

**Comment by mandarjog** [comment]
@lizan
1. This makes you update the workspace file locally; which I was trying to avoid.
2. I don't like the literal string as buildfile;  I have an alternative that is equivalent from a user's standpoint, but does not do the literal string.

**Comment by lizan** [comment]
1. It is the minimal change to avoid changing each BUILD file, another
approach is add a load statement to each BUILD. go_library doesn't work
without any source, so a dummy go_library target didn't work.

2. What is the equivalent? It is the easiest way to avoid copying BUILD
files around, especially when we have a repo (likely istio/istio) depends
on mixer, you don't have to copy BUILD for mixer dependencies to that repo.

**Comment by kyessenov** [comment]
So is the issue here you want to avoid pushing changes to api repo before trying them out in mixer?

Let's use gazella to automate BUILD file generations. Then if you use go tool, you can directly edit $GOROOT/.../api repo. If you use bazel, then there is a repo in /external/ that you can edit and Bazel accepts. What am I missing?

**Comment by douglas-reid** [comment]
iiuc, the issue is not wanting to edit the repo in /external/.

**Pull request merged**
