### PR TITLE
Introduce a general-purpose pool of bytes.Buffer objects.

### PR DESCRIPTION
**Pull request by geeknoid**
This change is [Reviewable](https://reviewable.io/reviews/istio/mixer/309)

### CODE REVIEW

**Comment by geeknoid** [comment]
Any suggestions for the names of such a combined package? With this PR, we
have:

intern.NewPool
buffer.Get
buffer.Put

Combined could be:

mem.NewStringPool
mem.GetBuffer
mem.PutBuffer

Other names?

**Comment by geeknoid** [comment]
Or maybe the package could be called pool:

pool.InternString
pool.GetBuffer
pool.PutBuffer

This would eliminate having multiple string pools in favor of one global string pool.

**Comment by ZackButcher** [comment]
`package pool` SGTM.

**Comment by douglas-reid** [comment]
pool seems reasonable.

**Comment by geeknoid** [comment]
PTAL.

**Comment by ZackButcher** [comment]
Long term I think we'll want to group buffers by the size of their underlying array, like we do for strings, but that's probably overkill right now.

**Pull request merged**
