### PR TITLE
Refactor mixer server to expose a common setup method for test env

### PR DESCRIPTION
**Pull request by manlinl**
**Release note**:

```release-note
```

---
This change is [Reviewable](https://reviewable.io/reviews/istio/mixer/1190)

### CODE REVIEW

**Comment by geeknoid** [comment]
This is fine for short term, but longer term I don't like having any dependencies on command-line tools from outside. If we want to reuse the server startup glue code, we should create a separate package for that purpose.

**Comment by manlinl** [comment]
Agree, we should move the server startup code /mixer/pkg/somewhere

**Pull request merged**
