### PR TITLE
Remove legacy config files

### PR DESCRIPTION
**Pull request by douglas-reid**
These config files should no longer be used and are certainly not being kept in sync with the fs://$pwd/testdata/configroot configuration.

This PR removes them to prevent confusion and eliminate dead config files.

---
This change is [Reviewable](https://reviewable.io/reviews/istio/mixer/765)

### CODE REVIEW

**Comment by douglas-reid** [comment]
build mixer/e2e-smoketest

**Comment by douglas-reid** [comment]
@sebastienvas i can't seem to trigger the smoketest (either from the comments here or from testing.istio.io). can you help?

**Comment by sebastienvas** [comment]
build mixer/e2e-smoketest

**Comment by sebastienvas** [comment]
build mixer/e2e-smoketest

**Pull request merged**
