### PR TITLE
Add attribute.Bag to allow mixer-based mutation of attributes.

### PR DESCRIPTION
**Pull request by geeknoid**
---
This change is [Reviewable](https://reviewable.io/reviews/istio/mixer/98)

### CODE REVIEW

**Comment by mandarjog** [comment]
*[pkg/attribute/overrider.go, line 23 at r1](https://reviewable.io:443/reviews/istio/mixer/98#-KZbZxb64a1fXIhdxJT1:-KZbZxb64a1fXIhdxJT2:bmhodvc) ([raw file](https://github.com/istio/mixer/blob/9f86be873ef8dd5b322f9eaa877b863881f3bea8/pkg/attribute/overrider.go#L23)):*
> ```Go
> // Overrider is a generic mechanism to locally override attribute
> // valuesvfrom a context, without mutating the underlying context.
> type Overrider interface {
> ```

I think mutable is a more appropriate name.
```go
type MutableContext interface {
SetXX fns

Context
}
```

In my view there is chain of Contexts, the last one of which is mutable.
There is a 
- global attribute context
- per input stream attribute context
- per message attribute context

At this point request processing starts.

Here we *want* mutable context because aspectImpls may be ordered and one may depend on certain attributes to be present that were injected earlier.

The adapter managers should be passed in mutableContext. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/istio/mixer/98)*

**Comment by geeknoid** [comment]
Updated the model. The immutable Context interface is gone, replaced with the mutable Bag interface. The context is still maintained internally, it represents the exact set of attributes exchanged from the proxy to the mixer. The Bag instead represents the mixer's ongoing mutation to those attributes as they travel down different pipelines.

**Comment by mandarjog** [comment]
*[pkg/attribute/bag.go, line 63 at r2](https://reviewable.io:443/reviews/istio/mixer/98#-KZbpCwCN1h93ajUQUt_:-KZbpCwCN1h93ajUQUta:b-900xxh) ([raw file](https://github.com/istio/mixer/blob/184517a8a28ab48c77cc039b388d84fa44385da2/pkg/attribute/bag.go#L63)):*
> ```Go
> }
> 
> type bag struct {
> ```

 
1. At present there is 2 step process of chained contexts.
    But there is at least 1 more.  Why not model it as a chain.

   a. attributes established during connection phase at don't change. (like the identity of the caller)   {we are missing this }
    b. The exact attribute snapshot that was sent by proxy to mixer   { context }
    c.  attributes added during request processing by adapters  { bag }
2. why the word 'bag' instead of 'context'.      I think the earlier name conveyed the concept better.

```go
Context interface {
    Mutable
    Immutable
    
}

context struct {
   Mutable
   Immutable
   parent Immutable
}

func (c *context) String(name string) (string, bool) {
	var r string
	var b bool
     
	if r, b = c.strings[name]; !b {
                if c.parent != nil {                            
		   r, b = c.parent.String(name)
                }
	}
	return r, b
}

func newContext(parent Immutable) {
     return &context{ parent: parent}
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/istio/mixer/98)*

**Comment by geeknoid** [comment]
Our current API/protocol has no notion of global attributes and I don't
think it's necessary. Every gRPC stream is orthogonal and even invariants
such as client name are sent as part of the normal communication exchange
between the proxy and server. I therefore don't see any case where we
actually would benefit from a more complex chain solution. I don't want to
build special purpose support for these global attributes since there is no
tangible benefit (more moving pieces, no real perf impact)

As for the name, it would like I can rename Context<->Bag if you'd rather
have the external package interface be called a Context. I don't see the
benefit of one over the other personally.

**Comment by geeknoid** [comment]
Regarding "context" vs. "bag", I forgot to mention about the API surface.

The API surface defines the notion of attribute context. The proxy can pick different contexts to interact with when it talks to the mixer. These contexts are only updated as directed by the proxy, the mixer needs to consider those immutable in order for the proxy->mixer protocol to work.

So within the mixer, I want to use the word "context" to match with the protocol/API surface. 

Now, instead of attribute.Bag, we could go with attribute.MutableContext but that's just longer and doesn't seem particularly more mnemonic to me.

**Comment by douglas-reid** [comment]
I still feel like we should be using the standard context constructs here. The WithValue() stuff should provide the appropriate overriding, etc. as needed.  What do we get out of providing our re-implementation of it (other than the myriad typed methods)?

**Comment by douglas-reid** [comment]
Removing myself from reviewers list, as I'll be OOO for a little while.

It sounds like we will be passing Contexts around now in the code (which should help with cancels and tracing) -- and that we may attach Bag or whatever to that mechanism, which seems fine to me.

@mandarjog you have the conn.

**Pull request closed without merging**
